[local]
localhost

[mongodb]
mongodb-dev.rakesh.bond

[catalogue]
catalogue-dev.rakesh.bond

[redis]
redis-dev.rakesh.bond

[user]
user-dev.rakesh.bond

[cart]
cart-dev.rakesh.bond

[mysql]
mysql-dev.rakesh.bond

[shipping]
shipping-dev.rakesh.bond

[rabbitmq]
rabbitmq-dev.rakesh.bond

[payment]
payment-dev.rakesh.bond

[frontend]
frontend-dev.rakesh.bond