- name: testing 1
  ansible.builtin.debug:
   msg: "Hi from test 1"

- name: testing 2
  ansible.builtin.degbug:
   msg: "Hi from test 2"

- name: testing 3
  ansible.builtin.debug:
   msg: "Hi from test 1"